In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 70.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 16.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 76.5 MB/s eta 0:00:00


In [ ]:
from transformers import BertForSequenceClassification
from transformers import BertTokenizer
import torch

tokenizer=BertTokenizer.from_pretrained('IDEA-CCNL/Erlangshen-Roberta-110M-Sentiment')
model=BertForSequenceClassification.from_pretrained('IDEA-CCNL/Erlangshen-Roberta-110M-Sentiment')

text='今天心情不好'

output=model(torch.tensor([tokenizer.encode(text)]))
print(torch.nn.functional.softmax(output.logits,dim=-1))


tensor([[0.9551, 0.0449]], grad_fn=<SoftmaxBackward0>)


In [ ]:
text='怎么个请法？”红菱的大脚指头勾动一下，又淘气又下贱。'

output=model(torch.tensor([tokenizer.encode(text)]))
print(torch.nn.functional.softmax(output.logits,dim=-1))

tensor([[0.9987, 0.0013]], grad_fn=<SoftmaxBackward0>)


In [ ]:
text='然而凭着顽强的毅力,她努力学习按摩技术,通过自学取得了大专文凭,成为嘉兴唯一一名盲人中医师。'

output=model(torch.tensor([tokenizer.encode(text)]))
print(torch.nn.functional.softmax(output.logits,dim=-1))

tensor([[0.6397, 0.3603]], grad_fn=<SoftmaxBackward0>)


In [ ]:
import numpy as np

# the data is stored as dictionary, and splitted into 'train', 'valid', 'test'
biased_data = np.load('/content/drive/MyDrive/bias in datasets/CORGI-PM-main/dataset/CORGI-PC_splitted_biased_corpus_v1.npy',allow_pickle=True).item()
print(biased_data.keys())

dict_keys(['train', 'valid', 'test'])


In [ ]:
print(biased_data['train'].keys())

dict_keys(['ori_sentence', 'edit_sentence', 'bias_labels'])


In [ ]:
print(biased_data['train']['ori_sentence'][:3])

['史更新从来也没有遇到过这样的绝境，从来也没有感到过这样没有办法，平常时候他能够跨过高山，凫过深水，敌人要跑他可以把他抓住，虎狼凶恶，他可以把它打死，史更新满可以称得起是一条战无不胜的钢铁汉子！可是今天这条汉子掉进这个小泥坑来没有办法了。'
 '“怎么个请法？”红菱的大脚指头勾动一下，又淘气又下贱。'
 '这不是我的下贱，可能是我的卑鄙，我幻想着如果他在那一刻真的认为我就是你，也许他会让我有孩子的。']


In [ ]:
print(biased_data['train']['edit_sentence'][:3])

['史更新从来也没有遇到过这样的绝境，从来也没有感到过这样没有办法，平常时候他能够跨过高山，凫过深水，敌人要跑他可以把他抓住，虎狼凶恶，他可以把它打死，史更新满可以称得起是一条战无不胜的勇敢汉子！可是今天这条汉子掉进这个小泥坑来没有办法了。'
 '“怎么个请法？”红菱的大脚指头勾动一下，又淘气又活泼。\t\t  评：用下贱形容女性极具贬义，体现了男权社会思维。'
 '这不是我的问题，可能是我的卑鄙，我幻想着如果他在那一刻真的认为我就是你，也许他会让我有孩子的。\t\t  评：用下贱来形容女性是对女性的极度不尊重，女性要孩子还需要男性允许留下来，体现了男女社会地位不平等。']


In [ ]:
print(biased_data['train']['bias_labels'][:3])

[[0 1 0]
 [0 1 1]
 [0 1 0]]


# Check some random examples:

In [ ]:
import random
 
index = random.randint(0,len(biased_data["valid"]['ori_sentence']))

print(index)
print(biased_data['valid']['ori_sentence'][index])
print(biased_data['valid']['edit_sentence'][index])

420
而男桌往往被叫做主桌，菜式最丰富，酒水最充足。
男女没有主次之分，男桌不应称之为主桌。


# Check the non-biased samples

In [ ]:
nonbiased_data = np.load('/content/drive/MyDrive/bias in datasets/CORGI-PM-main/dataset/CORGI-PC_splitted_non-bias_corpus_v1.npy',allow_pickle=True).item()
print(nonbiased_data.keys())

dict_keys(['train', 'valid', 'test'])


In [ ]:
print(nonbiased_data['train'].keys())

dict_keys(['unique_id', 'text'])


In [ ]:
print(nonbiased_data['train']['unique_id'][:5])
print(nonbiased_data['train']['text'][:5])

['N_SLGU_0014854', 'N_CCL_0005537', 'N_SLGU_0017288', 'N_SLGU_0015790', 'N_SLGU_0020479']
['然而凭着顽强的毅力,她努力学习按摩技术,通过自学取得了大专文凭,成为嘉兴唯一一名盲人中医师。', '胃。不过，在快要上场前向费拉葛斯握手致歉倒是很容易做得到，黑人接受了道歉。奇莉——很明显的已经从费拉葛斯口中知道了来龙去脉——则是微笑的看着两人。她闪灿的绿眼散发出对卡拉蒙装扮的高度欣赏，让他的脸浮上羞赧的酡红。', '看着老奶奶开心地笑，我心里也美滋滋的。', '天天与尿毒症病人打交道,她深知这病的危害,曾亲眼见一个大学生因慢性肾炎没有认真治疗而离世,要说没有恐惧,那不是真的。', '用人单位在录用职工或者改组、改制时，不得以任何理由歧视或者排斥女职工。']


## Word list

In [ ]:
word_list = ['男', '女']


In [ ]:
for split in ['train', 'valid', 'test']:
  count = 0
  for sent in biased_data[split]['ori_sentence']:
    for word in word_list:
      if word in sent:
        count += 1
  print("In biased data, {} set, {}% contain words in word list.".format(split, count / len(biased_data[split]['ori_sentence'])))

In biased data, train set, 0.6529242569511026% contain words in word list.
In biased data, valid set, 0.7984496124031008% contain words in word list.
In biased data, test set, 0.7140115163147792% contain words in word list.


In [ ]:
for split in ['train', 'valid', 'test']:
  count = 0
  for sent in nonbiased_data[split]['text']:
    for word in word_list:
      if word in sent:
        count += 1
  print("In non biased data, {} set, {}% contain words in word list.".format(split, count / len(nonbiased_data[split]['text'])))

In non biased data, train set, 0.2968531142030068% contain words in word list.
In non biased data, valid set, 0.28875968992248063% contain words in word list.
In non biased data, test set, 0.279467680608365% contain words in word list.
